### ISSUE TITLE
Licensor fails to register licences at startup

### ISSUE THREAD

**Issue by aubincleme** [xwikisas/application-licensing#152]
This issue has been observed on a client instance running XWiki 14.10.16 with XWiki installed on Debian through the standard deb package. I also reproduced the issue locally on a Jetty-HSQLDB, also in 14.10.16. The stacktraces produced are equivalent.

Steps to reproduce : 
* Start with a clean XWiki version
* Install Confluence Migrator Pro 1.0-rc-4
* Generate a licence for the migrator, deploy it on the wiki (everything should be ok until now)
* In the extension manager, upgrade the Confluence Migrator pro to 1.0
* Restart the wiki
* Observe that the licensor does not register any active licence and produces the stacktrace below

I'm marking this issue as blocker as it can be a real problem if it reproduces for pro apps that are related to authentication, such as the Azure SSO or the Active Directory app.

Note : I have not checked starting an instance from scratch 

```
2023-09-27 23:14:20,251 [main] WARN  c.x.l.i.DefaultLicenseManager  - Error registering license, license has been skipped. 
org.xwiki.component.manager.ComponentLookupException: Failed to lookup component [org.xwiki.instance.internal.DefaultInstanceIdManager] identified by type [interface org.xwiki.instance.InstanceIdManager] and hint [default]
	at org.xwiki.component.embed.EmbeddableComponentManager.getInstance(EmbeddableComponentManager.java:204)
	at org.xwiki.component.embed.GenericProvider.getInstance(GenericProvider.java:111)
	at org.xwiki.component.embed.GenericProvider.get(GenericProvider.java:100)
	at com.xwiki.licensing.internal.DefaultLicenseValidator.isApplicable(DefaultLicenseValidator.java:83)
	at com.xwiki.licensing.internal.DefaultLicenseManager.linkLicenseToLicensedFeature(DefaultLicenseManager.java:206)
	at com.xwiki.licensing.internal.DefaultLicenseManager.initialize(DefaultLicenseManager.java:147)
	at org.xwiki.component.embed.InitializableLifecycleHandler.handle(InitializableLifecycleHandler.java:39)
	at org.xwiki.component.embed.EmbeddableComponentManager.createInstance(EmbeddableComponentManager.java:365)
	at org.xwiki.component.embed.EmbeddableComponentManager.getComponentInstance(EmbeddableComponentManager.java:451)
	at org.xwiki.component.embed.EmbeddableComponentManager.getInstance(EmbeddableComponentManager.java:201)
	at org.xwiki.component.embed.EmbeddableComponentManager.getDependencyInstance(EmbeddableComponentManager.java:406)
	at org.xwiki.component.embed.EmbeddableComponentManager.createInstance(EmbeddableComponentManager.java:355)
	at org.xwiki.component.embed.EmbeddableComponentManager.getComponentInstance(EmbeddableComponentManager.java:451)
	at org.xwiki.component.embed.EmbeddableComponentManager.getInstance(EmbeddableComponentManager.java:201)
	at org.xwiki.component.embed.EmbeddableComponentManager.getInstance(EmbeddableComponentManager.java:210)
	at org.xwiki.component.embed.EmbeddableComponentManager.getDependencyInstance(EmbeddableComponentManager.java:406)
	at org.xwiki.component.embed.EmbeddableComponentManager.createInstance(EmbeddableComponentManager.java:355)
	at org.xwiki.component.embed.EmbeddableComponentManager.getComponentInstance(EmbeddableComponentManager.java:451)
	at org.xwiki.component.embed.EmbeddableComponentManager.getInstance(EmbeddableComponentManager.java:201)
	at org.xwiki.observation.internal.DefaultObservationManager.onEventListenerComponentAdded(DefaultObservationManager.java:383)
	at org.xwiki.observation.internal.DefaultObservationManager.onComponentEvent(DefaultObservationManager.java:354)
	at org.xwiki.observation.internal.DefaultObservationManager.notify(DefaultObservationManager.java:299)
	at org.xwiki.component.internal.StackingComponentEventManager.sendEvent(StackingComponentEventManager.java:151)
	at org.xwiki.component.internal.StackingComponentEventManager.flushEvents(StackingComponentEventManager.java:92)
	at org.xwiki.container.servlet.XWikiServletContextListener.contextInitialized(XWikiServletContextListener.java:133)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:1043)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:624)
	at org.eclipse.jetty.server.handler.ContextHandler.contextInitialized(ContextHandler.java:978)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:705)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:392)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1304)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:895)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:306)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:532)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:40)
	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:183)
	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:516)
	at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:151)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:186)
	at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:462)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:58)
	at org.eclipse.jetty.util.Scanner$DiscreteListener.pathAdded(Scanner.java:282)
	at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:836)
	at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:802)
	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:709)
	at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:597)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:121)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:158)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:605)
	at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:246)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
	at org.eclipse.jetty.server.Server.start(Server.java:469)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:121)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89)
	at org.eclipse.jetty.server.Server.doStart(Server.java:414)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.xml.XmlConfiguration.lambda$main$4(XmlConfiguration.java:1867)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1810)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.jetty.start.Main.invokeMain(Main.java:227)
	at org.eclipse.jetty.start.Main.start(Main.java:512)
	at org.eclipse.jetty.start.Main.main(Main.java:74)
Caused by: java.lang.NullPointerException: null
	at org.xwiki.instance.internal.DefaultInstanceIdManager.getXWikiContext(DefaultInstanceIdManager.java:145)
	at org.xwiki.instance.internal.DefaultInstanceIdManager.initialize(DefaultInstanceIdManager.java:94)
	at org.xwiki.component.embed.InitializableLifecycleHandler.handle(InitializableLifecycleHandler.java:39)
	at org.xwiki.component.embed.EmbeddableComponentManager.createInstance(EmbeddableComponentManager.java:365)
	at org.xwiki.component.embed.EmbeddableComponentManager.getComponentInstance(EmbeddableComponentManager.java:451)
	at org.xwiki.component.embed.EmbeddableComponentManager.getInstance(EmbeddableComponentManager.java:201)
	... 70 common frames omitted
2023-09-27 23:14:20,260 [main] WARN  c.x.l.i.DefaultLicenseManager  - Error registering license, license has been skipped. 
org.xwiki.component.manager.ComponentLookupException: Failed to lookup component [org.xwiki.instance.internal.DefaultInstanceIdManager] identified by type [interface org.xwiki.instance.InstanceIdManager] and hint [default]
	at org.xwiki.component.embed.EmbeddableComponentManager.getInstance(EmbeddableComponentManager.java:204)
	at org.xwiki.component.embed.GenericProvider.getInstance(GenericProvider.java:111)
	at org.xwiki.component.embed.GenericProvider.get(GenericProvider.java:100)
	at com.xwiki.licensing.internal.DefaultLicenseValidator.isApplicable(DefaultLicenseValidator.java:83)
	at com.xwiki.licensing.internal.DefaultLicenseManager.linkLicenseToLicensedFeature(DefaultLicenseManager.java:206)
	at com.xwiki.licensing.internal.DefaultLicenseManager.initialize(DefaultLicenseManager.java:147)
	at org.xwiki.component.embed.InitializableLifecycleHandler.handle(InitializableLifecycleHandler.java:39)
	at org.xwiki.component.embed.EmbeddableComponentManager.createInstance(EmbeddableComponentManager.java:365)
	at org.xwiki.component.embed.EmbeddableComponentManager.getComponentInstance(EmbeddableComponentManager.java:451)
	at org.xwiki.component.embed.EmbeddableComponentManager.getInstance(EmbeddableComponentManager.java:201)
	at org.xwiki.component.embed.EmbeddableComponentManager.getDependencyInstance(EmbeddableComponentManager.java:406)
	at org.xwiki.component.embed.EmbeddableComponentManager.createInstance(EmbeddableComponentManager.java:355)
	at org.xwiki.component.embed.EmbeddableComponentManager.getComponentInstance(EmbeddableComponentManager.java:451)
	at org.xwiki.component.embed.EmbeddableComponentManager.getInstance(EmbeddableComponentManager.java:201)
	at org.xwiki.component.embed.EmbeddableComponentManager.getInstance(EmbeddableComponentManager.java:210)
	at org.xwiki.component.embed.EmbeddableComponentManager.getDependencyInstance(EmbeddableComponentManager.java:406)
	at org.xwiki.component.embed.EmbeddableComponentManager.createInstance(EmbeddableComponentManager.java:355)
	at org.xwiki.component.embed.EmbeddableComponentManager.getComponentInstance(EmbeddableComponentManager.java:451)
	at org.xwiki.component.embed.EmbeddableComponentManager.getInstance(EmbeddableComponentManager.java:201)
	at org.xwiki.observation.internal.DefaultObservationManager.onEventListenerComponentAdded(DefaultObservationManager.java:383)
	at org.xwiki.observation.internal.DefaultObservationManager.onComponentEvent(DefaultObservationManager.java:354)
	at org.xwiki.observation.internal.DefaultObservationManager.notify(DefaultObservationManager.java:299)
	at org.xwiki.component.internal.StackingComponentEventManager.sendEvent(StackingComponentEventManager.java:151)
	at org.xwiki.component.internal.StackingComponentEventManager.flushEvents(StackingComponentEventManager.java:92)
	at org.xwiki.container.servlet.XWikiServletContextListener.contextInitialized(XWikiServletContextListener.java:133)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:1043)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:624)
	at org.eclipse.jetty.server.handler.ContextHandler.contextInitialized(ContextHandler.java:978)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:705)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:392)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1304)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:895)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:306)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:532)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:40)
	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:183)
	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:516)
	at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:151)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:186)
	at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:462)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:58)
	at org.eclipse.jetty.util.Scanner$DiscreteListener.pathAdded(Scanner.java:282)
	at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:836)
	at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:802)
	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:709)
	at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:597)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:121)
	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:158)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:605)
	at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:246)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
	at org.eclipse.jetty.server.Server.start(Server.java:469)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:121)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89)
	at org.eclipse.jetty.server.Server.doStart(Server.java:414)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.xml.XmlConfiguration.lambda$main$4(XmlConfiguration.java:1867)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1810)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.jetty.start.Main.invokeMain(Main.java:227)
	at org.eclipse.jetty.start.Main.start(Main.java:512)
	at org.eclipse.jetty.start.Main.main(Main.java:74)
Caused by: java.lang.NullPointerException: null
	at org.xwiki.instance.internal.DefaultInstanceIdManager.getXWikiContext(DefaultInstanceIdManager.java:145)
	at org.xwiki.instance.internal.DefaultInstanceIdManager.initialize(DefaultInstanceIdManager.java:94)
	at org.xwiki.component.embed.InitializableLifecycleHandler.handle(InitializableLifecycleHandler.java:39)
	at org.xwiki.component.embed.EmbeddableComponentManager.createInstance(EmbeddableComponentManager.java:365)
	at org.xwiki.component.embed.EmbeddableComponentManager.getComponentInstance(EmbeddableComponentManager.java:451)
	at org.xwiki.component.embed.EmbeddableComponentManager.getInstance(EmbeddableComponentManager.java:201)
	... 70 common frames omitted
Exception in thread "XWiki License Manager Initialization Thread" java.lang.NullPointerException
	at org.xwiki.security.internal.DefaultXWikiBridge.getMainWikiReference(DefaultXWikiBridge.java:66)
	at org.xwiki.security.DefaultSecurityReferenceFactory.getMainWikiReference(DefaultSecurityReferenceFactory.java:55)
	at org.xwiki.security.DefaultSecurityReferenceFactory.newEntityReference(DefaultSecurityReferenceFactory.java:65)
	at com.xwiki.licensing.internal.enforcer.DefaultLicensingSecurityCacheRuleInvalidator.invalidateForWiki(DefaultLicensingSecurityCacheRuleInvalidator.java:98)
	at com.xwiki.licensing.internal.enforcer.DefaultLicensingSecurityCacheRuleInvalidator.invalidate(DefaultLicensingSecurityCacheRuleInvalidator.java:72)
	at com.xwiki.licensing.internal.DefaultLicenseManager.clearSecurityCacheForXarExtension(DefaultLicenseManager.java:353)
	at com.xwiki.licensing.internal.DefaultLicenseManager.access$500(DefaultLicenseManager.java:67)
	at com.xwiki.licensing.internal.DefaultLicenseManager$LinkLicenseToInstalledExtensionsRunnable.run(DefaultLicenseManager.java:89)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by mflorea** [comment]
@aubincleme this is actually a bug in the Confluence Migrator Pro:

* it injects the ``Licensor`` in an **event listener** https://github.com/xwikisas/application-confluence-migrator-pro/blob/application-confluence-migrator-pro-1.0/application-confluence-migrator-pro-default/src/main/java/com/xwiki/confluencepro/internal/ConfluenceFilteringListener.java#L65
* event listeners (components) are initialized very early, before the XWiki / Execution context is initialized
* when ``ConfluenceFilteringListener`` component is initialized it triggers the initialization of the ``Licensor`` which triggers the initialization of the ``LicenseManager``
* the ``LicenseManager`` needs the ``InstanceIdManager`` to work which can be initialized only after the database is ready (i.e. only after the XWiki / Execution context is initialized)

The solution is simple: ``ConfluenceFilteringListener`` should inject instead ``Provider<Licensor>``.

We cannot simply change (without some refactoring) the ``Licensor`` to use ``Provider<LicenseManager>`` because the ``Licensor`` currently has an initialization method that checks the integrity of the ``LicenseManager`` so the ``LicenseManager`` needs to be initialized before the ``Licensor``.

**Comment by mflorea** [comment]
I reported https://github.com/xwikisas/application-confluence-migrator-pro/issues/15 .
