### ISSUE TITLE
NullPointerException in DefaultLicenseManager initialization code if a licensed extension is badly installed

### ISSUE THREAD

**Issue by mflorea** [xwikisas/application-licensing#25]
If a licensed extension is badly installed due to ['Random "zip file closed" error while upgrading/downgrading a JAR extension, causes the wiki to be unusable' (XWIKI-14151)](https://jira.xwiki.org/browse/XWIKI-14151) then the ``DefaultLicenseManager`` throws a NPE in its initialization code:

    2018-02-21 14:36:37,150 [http://localhost:10080/xwiki/bin/view/Main/] ERROR .a.DefaultAuthorizationManager - Failed to load rights for user [xwiki:XWiki.Admin] on [xwiki:XWiki.Notifications.Code.NotificationsDisplayerUIX].
    java.lang.RuntimeException: Failed to get [role = [interface com.xwiki.licensing.LicenseManager] hint = [default]]
    at org.xwiki.component.embed.GenericProvider.get(GenericProvider.java:103)
    at com.xwiki.licensing.internal.enforcer.DefaultEntityLicenseManager.getLicenseManager(DefaultEntityLicenseManager.java:79)
    at com.xwiki.licensing.internal.enforcer.DefaultEntityLicenseManager.getLicenses(DefaultEntityLicenseManager.java:103)
    at com.xwiki.licensing.internal.enforcer.DefaultEntityLicenseManager.get(DefaultEntityLicenseManager.java:91)
    at com.xwiki.licensing.internal.enforcer.LicensingSecurityEntryReader.read(LicensingSecurityEntryReader.java:160)
    at org.xwiki.security.authorization.cache.internal.DefaultSecurityCacheLoader.getRules(DefaultSecurityCacheLoader.java:450)
    at org.xwiki.security.authorization.cache.internal.DefaultSecurityCacheLoader.loadRequiredEntries(DefaultSecurityCacheLoader.java:193)
    at org.xwiki.security.authorization.cache.internal.DefaultSecurityCacheLoader.load(DefaultSecurityCacheLoader.java:149)
    at org.xwiki.security.authorization.DefaultAuthorizationManager.getAccess(DefaultAuthorizationManager.java:209)
    at org.xwiki.security.authorization.DefaultAuthorizationManager.evaluateSecurityAccess(DefaultAuthorizationManager.java:159)
    at org.xwiki.security.authorization.DefaultAuthorizationManager.hasSecurityAccess(DefaultAuthorizationManager.java:152)
    at org.xwiki.security.authorization.DefaultAuthorizationManager.hasAccess(DefaultAuthorizationManager.java:109)
    at org.xwiki.security.authorization.internal.DefaultContextualAuthorizationManager.hasAccess(DefaultContextualAuthorizationManager.java:136)
    at org.xwiki.security.authorization.internal.DefaultContextualAuthorizationManager.hasAccess(DefaultContextualAuthorizationManager.java:131)
    at com.xpn.xwiki.plugin.skinx.AbstractDocumentSkinExtensionPlugin.isAccessible(AbstractDocumentSkinExtensionPlugin.java:393)
    at com.xpn.xwiki.plugin.skinx.CssSkinExtensionPlugin.getLink(CssSkinExtensionPlugin.java:80)
    at com.xpn.xwiki.plugin.skinx.AbstractSkinExtensionPlugin.getImportString(AbstractSkinExtensionPlugin.java:253)
    at com.xpn.xwiki.plugin.skinx.AbstractSkinExtensionPlugin.endParsing(AbstractSkinExtensionPlugin.java:354)
    at com.xpn.xwiki.plugin.skinx.AbstractDocumentSkinExtensionPlugin.endParsing(AbstractDocumentSkinExtensionPlugin.java:284)
    at com.xpn.xwiki.plugin.skinx.CssSkinExtensionPlugin.endParsing(CssSkinExtensionPlugin.java:114)
    at com.xpn.xwiki.plugin.XWikiPluginManager.endParsing(XWikiPluginManager.java:275)
    at com.xpn.xwiki.web.Utils.parseTemplate(Utils.java:184)
    at com.xpn.xwiki.web.Utils.parseTemplate(Utils.java:88)
    at com.xpn.xwiki.web.XWikiAction.execute(XWikiAction.java:486)
    at com.xpn.xwiki.web.XWikiAction.execute(XWikiAction.java:209)
    at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:425)
    at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:228)
    at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1913)
    at org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:449)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:860)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
    at com.xpn.xwiki.web.ActionFilter.doFilter(ActionFilter.java:112)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
    at org.xwiki.wysiwyg.filter.ConversionFilter.doFilter(ConversionFilter.java:127)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
    at org.xwiki.container.servlet.filters.internal.SetHTTPHeaderFilter.doFilter(SetHTTPHeaderFilter.java:63)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
    at org.xwiki.container.servlet.filters.internal.SavedRequestRestorerFilter.doFilter(SavedRequestRestorerFilter.java:208)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
    at org.xwiki.container.servlet.filters.internal.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:111)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
    at org.xwiki.resource.servlet.RoutingFilter.doFilter(RoutingFilter.java:134)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1629)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
    at org.eclipse.jetty.server.Server.handle(Server.java:530)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
    at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
    at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
    at java.lang.Thread.run(Thread.java:745)
    Caused by: org.xwiki.component.manager.ComponentLookupException: Failed to lookup component [com.xwiki.licensing.internal.DefaultLicenseManager] identified by type [interface com.xwiki.licensing.LicenseManager] and hint [default]
    at org.xwiki.component.embed.EmbeddableComponentManager.getInstance(EmbeddableComponentManager.java:199)
    at org.xwiki.component.embed.GenericProvider.getInstance(GenericProvider.java:111)
    at org.xwiki.component.embed.GenericProvider.get(GenericProvider.java:100)
    ... 74 common frames omitted
    Caused by: java.lang.NullPointerException: null

This is quite serious because the problem persists after a restart and it prevents the access to the wiki because rights can't be loaded as a consequence. The workaround is to remove the broken extension from XWiki's permanent directory (e.g. ``data/extension/repository``) and restart.

**Comment by mflorea** [comment]
Duplicate of #29.
