### ISSUE TITLE
NPE on DefaultLicenseManager when upgrading an XWiki instance

### ISSUE THREAD

**Issue by ilieandriuta** [xwikisas/application-licensing#42]
STEPS TO REPRODUCE

Preconditions: An instance of XWiki 8.4.6 and an instance of XWiki 10.3 (to which will be migrated) are available.

1. Go to the older instance and install a Paid Application, e.g. Forum Application (Pro)
2. Close the instance
3. Go to the newer instance (e.g. 10.3) and copy/cut the `[...]webapps\xwiki` folder and replace it (first delete the old one) in the same location on the older version
4. Start the instance and follow the Distribution Wizard through the upgrade process

EXPECTED RESULTS

The upgrade process is completed successfully without errors.

ACTUAL RESULTS

In install log there is encountered an error related to a NullPointerException on DefaultLicenseManager, which appears several times, having the following stacktrace:

`Failed to send event [org.xwiki.extension.event.ExtensionUpgradedEvent@5d352c0d] to listener [com.xwiki.licensing.internal.LicenseManagerEventListener@9911c3e]
class java.lang.NullPointerException: null
    at com.xwiki.licensing.internal.DefaultLicenseManager.uninstallExtensionLicense(DefaultLicenseManager.java:322)
    at com.xwiki.licensing.internal.LicenseManagerEventListener.onEvent(LicenseManagerEventListener.java:92)
    at org.xwiki.observation.internal.DefaultObservationManager.notify(DefaultObservationManager.java:304)
    at org.xwiki.observation.internal.DefaultObservationManager.notify(DefaultObservationManager.java:269)
    at org.xwiki.extension.job.internal.AbstractExtensionJob.installExtension(AbstractExtensionJob.java:339)
    at org.xwiki.extension.job.internal.AbstractExtensionJob.applyAction(AbstractExtensionJob.java:209)
    at org.xwiki.extension.job.internal.AbstractExtensionJob.applyActions(AbstractExtensionJob.java:157)
    at org.xwiki.extension.job.internal.InstallJob.runInternal(InstallJob.java:154)
    at org.xwiki.job.AbstractJob.runInContext(AbstractJob.java:206)
    at org.xwiki.job.AbstractJob.run(AbstractJob.java:189)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)`

However, after upgrade process is finished, the license appears to be valid.

Also, in the console there is a warning (not sure if it's related to the NPE) having the following stacktrace:

`2018-05-10 13:06:03,731 [XWiki Solr index thread] WARN  ngSecurityCacheRuleInvalidator - Failed to acquire read lock in LicensingSecurityCacheRuleInvalidator. Continuing without lock. `

Please find attached the console log and the screenshot.

[2018_05_10.output.log](https://github.com/xwikisas/application-licensing/files/1991344/2018_05_10.output.log)

![licensemanager_listener_error](https://user-images.githubusercontent.com/32512703/39866524-b7ce39da-5459-11e8-953a-2e5a8e8c99b8.jpg)

**Comment by acotiuga** [comment]
This issue duplicates https://github.com/xwikisas/application-licensing/issues/47. A fix has been provided.
