### ISSUE TITLE
Programming rights error appears in the log when creating a subwiki with a user who has only wiki rights and a PRO app was installed 

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-licensing#58]
Steps to reproduce:

1. Log in as Admin
2. Create a simple user
3. Give it wiki creation rights
4. Install a PRO app eg. Forum, Diagram, Ideas
5. Log in as the simple user
6. Create a new subiki with Standard Flavor and default options
7. Observe the creation log

Expected results: The subwiki is created with no errors.

Actual results: An error appears in the creation log

`Access denied when checking [programming] access to [Main Wiki] for user [xwiki:XWiki.user01] 
class org.xwiki.security.authorization.AccessDeniedException: Access denied when checking [programming] access to [Main Wiki] for user [xwiki:XWiki.user01]
    at org.xwiki.security.authorization.DefaultAuthorizationManager.checkAccess(DefaultAuthorizationManager.java:94)
    at org.xwiki.localization.wiki.internal.DocumentTranslationBundleFactory.checkRegistrationAuthorization(DocumentTranslationBundleFactory.java:439)
    at org.xwiki.localization.wiki.internal.DocumentTranslationBundleFactory.registerTranslationBundle(DocumentTranslationBundleFactory.java:418)
    at org.xwiki.localization.wiki.internal.DocumentTranslationBundleFactory.translationDocumentUpdated(DocumentTranslationBundleFactory.java:346)
    at org.xwiki.localization.wiki.internal.DocumentTranslationBundleFactory.access$000(DocumentTranslationBundleFactory.java:86)
    at org.xwiki.localization.wiki.internal.DocumentTranslationBundleFactory$1.onEvent(DocumentTranslationBundleFactory.java:156)
    at org.xwiki.observation.internal.DefaultObservationManager.notify(DefaultObservationManager.java:309)
    at org.xwiki.observation.internal.DefaultObservationManager.notify(DefaultObservationManager.java:274)
    at com.xpn.xwiki.XWiki.saveDocument(XWiki.java:1904)
    at org.xwiki.extension.xar.internal.handler.packager.DocumentMergeImporter.saveDocumentSetContextUser(DocumentMergeImporter.java:207)
    at org.xwiki.extension.xar.internal.handler.packager.DocumentMergeImporter.saveDocument(DocumentMergeImporter.java:153)
    at org.xwiki.extension.xar.internal.handler.packager.DocumentMergeImporter.importDocument(DocumentMergeImporter.java:116)
    at org.xwiki.extension.xar.internal.handler.packager.Packager.importDocumentToWiki(Packager.java:230)
    at org.xwiki.extension.xar.internal.handler.packager.Packager.importXARToWiki(Packager.java:188)
    at org.xwiki.extension.xar.internal.handler.packager.Packager.importXARToWiki(Packager.java:157)
    at org.xwiki.extension.xar.internal.handler.packager.Packager.importXAR(Packager.java:148)
    at org.xwiki.extension.xar.internal.handler.XarExtensionHandler.installInternal(XarExtensionHandler.java:201)
    at org.xwiki.extension.xar.internal.handler.XarExtensionHandler.install(XarExtensionHandler.java:166)
    at org.xwiki.extension.handler.internal.DefaultExtensionHandlerManager.install(DefaultExtensionHandlerManager.java:85)
    at org.xwiki.extension.job.internal.AbstractExtensionJob.installExtension(AbstractExtensionJob.java:306)
    at org.xwiki.extension.job.internal.AbstractExtensionJob.applyAction(AbstractExtensionJob.java:209)
    at org.xwiki.extension.job.internal.AbstractExtensionJob.applyActions(AbstractExtensionJob.java:157)
    at org.xwiki.extension.job.internal.InstallJob.runInternal(InstallJob.java:154)
    at org.xwiki.job.AbstractJob.runInContext(AbstractJob.java:236)
    at org.xwiki.job.AbstractJob.run(AbstractJob.java:213)
    at org.xwiki.platform.wiki.creationjob.internal.ExtensionInstaller.installExtension(ExtensionInstaller.java:73)
    at org.xwiki.platform.wiki.creationjob.internal.steps.ProvisionWikiStep.execute(ProvisionWikiStep.java:78)
    at org.xwiki.platform.wiki.creationjob.internal.WikiCreationJob.runInternal(WikiCreationJob.java:96)
    at org.xwiki.job.AbstractJob.runInContext(AbstractJob.java:236)
    at org.xwiki.job.AbstractJob.run(AbstractJob.java:213)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)`

Environment: Windows 10, XWiki 11.3 and 10.11.7 with MySQL 5.7 and Standard, Edge 18

![SimpleUserSubwiki10 11 7](https://user-images.githubusercontent.com/40691112/57286689-7aed9b00-70be-11e9-9ca3-bcc956583693.jpg)
![SimpleUserSubwiki11 3](https://user-images.githubusercontent.com/40691112/57286691-7aed9b00-70be-11e9-8a49-2797e7764586.jpg)

**NOTE:** The error appears only after installing a PRO app. Tried to create a subwiki with no PRO aps and it works with no errors.

**Comment by acotiuga** [comment]
This issue is not reproducing in XWiki 11.5. This may be related to https://jira.xwiki.org/browse/XWIKI-16370, which was fixed.
