### ISSUE TITLE
Installing the Licensing Application on XWiki older than 10.9 fails

### ISSUE THREAD

**Issue by mflorea** [xwikisas/application-licensing#67]
We get the following error:

```
org.xwiki.filter.FilterException: Failed to read XAR XML document
 at org.xwiki.filter.xar.internal.input.XARInputFilterStream.readDocument(XARInputFilterStream.java:122)
 at org.xwiki.filter.xar.internal.input.XARInputFilterStream.read(XARInputFilterStream.java:70)
 at org.xwiki.filter.xar.internal.input.XARInputFilterStream.read(XARInputFilterStream.java:47)
 at org.xwiki.filter.input.AbstractBeanInputFilterStream.read(AbstractBeanInputFilterStream.java:79)
 at org.xwiki.extension.xar.internal.handler.packager.Packager.getXWikiDocument(Packager.java:343)
 at org.xwiki.extension.xar.internal.handler.packager.Packager.importDocumentToWiki(Packager.java:199)
 at org.xwiki.extension.xar.internal.handler.packager.Packager.importXARToWiki(Packager.java:175)
 at org.xwiki.extension.xar.internal.handler.packager.Packager.importXARToWiki(Packager.java:146)
 at org.xwiki.extension.xar.internal.handler.packager.Packager.importXAR(Packager.java:133)
 at org.xwiki.extension.xar.internal.handler.XarExtensionHandler.installInternal(XarExtensionHandler.java:203)
 at org.xwiki.extension.xar.internal.handler.XarExtensionHandler.install(XarExtensionHandler.java:167)
 at org.xwiki.extension.handler.internal.DefaultExtensionHandlerManager.install(DefaultExtensionHandlerManager.java:85)
 at org.xwiki.extension.job.internal.AbstractExtensionJob.installExtension(AbstractExtensionJob.java:268)
 at org.xwiki.extension.job.internal.AbstractExtensionJob.applyAction(AbstractExtensionJob.java:201)
 at org.xwiki.extension.job.internal.AbstractExtensionJob.applyActions(AbstractExtensionJob.java:151)
 at org.xwiki.extension.job.internal.InstallJob.runInternal(InstallJob.java:150)
 at org.xwiki.job.AbstractJob.runInContext(AbstractJob.java:206)
 at org.xwiki.job.AbstractJob.run(AbstractJob.java:189)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
 at org.xwiki.filter.instance.internal.output.XWikiDocumentOutputFilterStream.onWikiClassPropertyField(XWikiDocumentOutputFilterStream.java:572)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
 at org.xwiki.filter.internal.FilterProxy.invoke(FilterProxy.java:90)
 at org.xwiki.filter.internal.FilterProxy.invoke(FilterProxy.java:63)
 at com.sun.proxy.$Proxy78.onWikiClassPropertyField(Unknown Source)
 at org.xwiki.filter.xar.internal.input.ClassPropertyReader$WikiClassProperty.send(ClassPropertyReader.java:57)
 at org.xwiki.filter.xar.internal.input.ClassReader$WikiClass.send(ClassReader.java:61)
 at org.xwiki.filter.xar.internal.input.WikiObjectReader$WikiObject.send(WikiObjectReader.java:85)
 at org.xwiki.filter.xar.internal.input.DocumentLocaleReader.sendWikiObjects(DocumentLocaleReader.java:522)
 at org.xwiki.filter.xar.internal.input.DocumentLocaleReader.readDocument(DocumentLocaleReader.java:467)
 at org.xwiki.filter.xar.internal.input.DocumentLocaleReader.read(DocumentLocaleReader.java:352)
 at org.xwiki.filter.xar.internal.input.DocumentLocaleReader.read(DocumentLocaleReader.java:325)
 at org.xwiki.filter.xar.internal.input.XARInputFilterStream.readDocument(XARInputFilterStream.java:120)
```

**Comment by mflorea** [comment]
Regression caused by #60. We need to pay more attention when committing wiki pages exported from a newer version of XWiki. The following meta properties are know to create problems:

* ``hint`` (9.11RC1+)
* ``defaultValue`` (10.9+)
* ``freeText`` (10.11RC1+)
* ``largeStorage`` (11.5RC1+)
