### ISSUE TITLE
A warning is displayed  in the logs when an "invalid" license is on the server

### ISSUE THREAD

**Issue by CamiAndrei** [xwikisas/application-licensing#83]
On the server are multiple licenses:
* An active license that is applied for the extensions.
* An expired license or with expired certificates.

Warning in the logs: 
`[XWiki initialization] WARN c.x.l.i.LicenseConverter - The signed license [cf80d6d2-a028-4fbf-a52d-e345175c114c] will not be used because its signature is not trusted.
java.lang.IllegalArgumentException: Invalid signed license data received. Signature not trusted.
at com.xwiki.licensing.SignedLicense.<init>(SignedLicense.java:72)
at com.xwiki.licensing.internal.LicenseConverter.convertToLicense(LicenseConverter.java:84)
at com.xwiki.licensing.internal.LicenseConverter.convertToType(LicenseConverter.java:75)
at com.xwiki.licensing.internal.LicenseConverter.convertToType(LicenseConverter.java:58)
at org.xwiki.properties.converter.AbstractConverter.convert(AbstractConverter.java:52)
at com.xwiki.licensing.internal.FileSystemLicenseStore$LicenseFileIterator.computeNext(FileSystemLicenseStore.java:239)
at com.xwiki.licensing.internal.FileSystemLicenseStore$LicenseFileIterator.hasNext(FileSystemLicenseStore.java:250)
at com.xwiki.licensing.internal.DefaultLicenseManager.initialize(DefaultLicenseManager.java:144)
at org.xwiki.component.embed.InitializableLifecycleHandler.handle(InitializableLifecycleHandler.java:39)
at org.xwiki.component.embed.EmbeddableComponentManager.createInstance(EmbeddableComponentManager.java:360)
at org.xwiki.component.embed.EmbeddableComponentManager.getComponentInstance(EmbeddableComponentManager.java:446)
at org.xwiki.component.embed.EmbeddableComponentManager.getInstance(EmbeddableComponentManager.java:196)
at org.xwiki.component.embed.EmbeddableComponentManager.getDependencyInstance(EmbeddableComponentManager.java:401)
at org.xwiki.component.embed.EmbeddableComponentManager.createInstance(EmbeddableComponentManager.java:350)
at org.xwiki.component.embed.EmbeddableComponentManager.getComponentInstance(EmbeddableComponentManager.java:446)
at org.xwiki.component.embed.EmbeddableComponentManager.getInstance(EmbeddableComponentManager.java:196)
at org.xwiki.component.embed.EmbeddableComponentManager.getInstance(EmbeddableComponentManager.java:205)
at org.xwiki.component.internal.multi.DelegateComponentManager.getInstance(DelegateComponentManager.java:83)
at org.xwiki.component.internal.multi.DelegateComponentManager.getInstance(DelegateComponentManager.java:83)
at org.xwiki.component.internal.multi.DelegateComponentManager.getInstance(DelegateComponentManager.java:83)
at org.xwiki.component.internal.multi.DelegateComponentManager.getInstance(DelegateComponentManager.java:83)
at org.xwiki.component.internal.multi.DelegateComponentManager.getInstance(DelegateComponentManager.java:83)
at com.xpn.xwiki.web.Utils.getComponent(Utils.java:753)
at com.xpn.xwiki.web.Utils.getComponent(Utils.java:778)
at com.xpn.xwiki.web.Utils.getComponent(Utils.java:731)
at com.xwiki.activedirectory.internal.ActiveDirectoryAuthServiceImpl.<init>(ActiveDirectoryAuthServiceImpl.java:50)
at com.xwiki.activedirectory.internal.ActiveDirectorySetupListener.setAuthService(ActiveDirectorySetupListener.java:119)
at com.xwiki.activedirectory.internal.ActiveDirectorySetupListener.onEvent(ActiveDirectorySetupListener.java:98)
at org.xwiki.observation.internal.DefaultObservationManager.notify(DefaultObservationManager.java:304)
at org.xwiki.observation.internal.DefaultObservationManager.notify(DefaultObservationManager.java:269)
at com.xpn.xwiki.internal.XWikiInitializerJob.runInternal(XWikiInitializerJob.java:131)
at org.xwiki.job.AbstractJob.runInContext(AbstractJob.java:206)
at org.xwiki.job.AbstractJob.run(AbstractJob.java:189)`

It doesn't affect the license or extension, just pollutes the logs. 
This issue relates with issue #53  .

**Comment by lamblinc** [comment]
This may come from the fact that old licenses are not deleted - couldn't we modify the behaviour to delete obsolete licences when checking for updates? Or at least add a button to get rid of them optionally?
